#!/usr/bin/env php
<?php

use Illuminate\Console\Application;

define('LARAVEL_START', microtime(true));

// Check if the application is in maintenance mode...
if (file_exists(__DIR__.'/storage/framework/maintenance.php')) {
    require __DIR__.'/storage/framework/maintenance.php';
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap the application and handle the command...
(require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new Symfony\Component\Console\Input\ArgvInput);
